### ISSUE TITLE
是否考虑过集成投屏sdk

### ISSUE THREAD

**Issue by cxhttt233** [SkyD666/Imomoe#1]
https://cloud.hpplay.cn/send.html
乐播云，实现也不算麻烦

**Comment by SkyD666** [comment]
以后会考虑的👍

**Comment by SkyD666** [comment]
v1.0.5 已经实现在线视频投屏。高版本Android本地视频投屏会失败，原因未知，因此缓存视频暂不支持投屏

**Comment by cxhttt233** [comment]
号，感谢大佬！
