### ISSUE TITLE
数据获取失败

### ISSUE THREAD

**Issue by SCPf-166** [SkyD666/Imomoe#108]
经常会出现“第x集获取失败“的内容，而且就是在固定的几个时间点，跳过这个点也能继续观看，但是看到一半经常被这个打断很闹心。

**Comment by SkyD666** [comment]
这种情况一般是视频源或者网络的问题，尝试切换网络或者数据源试试

**Comment by SCPf-166** [comment]
切换到数据源1完全加载不出，其它的数据源好像都不兼容，软件说只支持2206242210，也就是我已经在用的数据源

**Comment by SkyD666** [comment]
那就没办法了🤔

**Comment by SCPf-166** [comment]
我试试看更新到最新版吧😥

**Comment by SkyD666** [comment]
你发个链接我试试

**Comment by SCPf-166** [comment]
> 你发个链接我试试

https://www.yhdmp.net/vp/8097-1-13.html
比如魔禁第一季我现在正在看，印象里是前几集op里一定会出现数据获取失败的信息，后面的因为我都跳过op了所以也不清楚

**Comment by SkyD666** [comment]
https://www.yhdmp.net/vp/8097-1-0.html
你看这个是不是1:41会卡住

**Comment by SkyD666** [comment]
我这里网页播放也卡，是资源的问题
