### ISSUE TITLE
bulid apk报错

### ISSUE THREAD

**Issue by shaohui93** [SkyD666/Imomoe#11]
![image](https://user-images.githubusercontent.com/24472038/127678722-91ffc695-e7e9-487b-9817-d55c3ffb4860.png)

我把 DLNACastService 这个类全部注释掉，就可以编译出来apk了，不知道这个类是干嘛的。

**Comment by SkyD666** [comment]
投屏用的类

**Comment by shaohui93** [comment]
不知道为啥会报错呀，是有什么依赖没加进来么。怎么可以解决啊。还有可以把secret文件放出来么，看下这个文件你是怎么写的，可以把你自己的签名啥的替换成无用字符，就看下结构。

**Comment by shaohui93** [comment]
> 投屏用的类

不知道为啥会报错呀，是有什么依赖没加进来么。怎么可以解决啊。还有可以把secret文件放出来么，看下这个文件你是怎么写的，可以把你自己的签名啥的替换成无用字符，就看下结构。

**Comment by SkyD666** [comment]
> > 投屏用的类
> 
> 不知道为啥会报错呀，是有什么依赖没加进来么。怎么可以解决啊。还有可以把secret文件放出来么，看下这个文件你是怎么写的，可以把你自己的签名啥的替换成无用字符，就看下结构。

大概是这样
def secret = [:]

def sign = [:]
sign.RELEASE_KEY_ALIAS = "xxx"
sign.RELEASE_KEY_PASSWORD = "xxx"
sign.RELEASE_STORE_PASSWORD = "xxx"
secret.sign = sign
ext.secret = secret

**Comment by shaohui93** [comment]
> > > 投屏用的类
> > 
> > 不知道为啥会报错呀，是有什么依赖没加进来么。怎么可以解决啊。还有可以把secret文件放出来么，看下这个文件你是怎么写的，可以把你自己的签名啥的替换成无用字符，就看下结构。
> 
> 大概是这样
> def secret = [:]
> 
> def sign = [:]
> sign.RELEASE_KEY_ALIAS = "xxx"
> sign.RELEASE_KEY_PASSWORD = "xxx"
> sign.RELEASE_STORE_PASSWORD = "xxx"
> secret.sign = sign
> ext.secret = secret
> 

好的谢谢

**Comment by WangPengZhan** [comment]
i  try build the project and  as throw  that secret.gradle can not be found

**Comment by SkyD666** [comment]
> i try build the project and as throw that secret.gradle can not be found

Because secret.gradle file includes some secret infomation, such as a key or a secret code. You can delete the lines which use the file.
