### ISSUE TITLE
部分番剧无法播放

### ISSUE THREAD

**Issue by ho229v3666** [SkyD666/Imomoe#12]
部分番剧无法播放，疑似是播放源获取有问题
eg. 摇曳百合，点兔无法播放

**Comment by SkyD666** [comment]
有视频链接吗

**Comment by ho229v3666** [comment]
http://www.yhdm.io/v/459-1.html
http://www.yhdm.io/v/1631-1.html

**Comment by SkyD666** [comment]
> http://www.yhdm.io/v/459-1.html
> http://www.yhdm.io/v/1631-1.html

貌似通过浏览器有无法观看视频

**Comment by SkyD666** [comment]
> http://www.yhdm.io/v/459-1.html
> http://www.yhdm.io/v/1631-1.html

貌似通过浏览器也无法看视频

**Comment by ho229v3666** [comment]
对啊，所以说是你的源有问题
https://www.yhdmp.net/vp/11137-1-0.html
https://www.yhdmp.net/vp/14189-1-0.html

**Comment by SkyD666** [comment]
初步打算用“自定义数据源”（还在完善中）功能解决

**Comment by ho229v3666** [comment]
如果可以的话，能不能单独写个源的json放到release里面

**Comment by SkyD666** [comment]
> 如果可以的话，能不能单独写个源的json放到release里面

没理解什么意思

**Comment by ho229v3666** [comment]
就是维护一个官方源列表，放在Release里面可以方便更新

**Comment by SkyD666** [comment]
> 就是维护一个官方源列表，放在Release里面可以方便更新

这个比较复杂，因为不同的网站网址链接不一样；网页html写法也不一样。不同的网站需要有不同的解析html逻辑。目前自定义数据源功能就是为了解决这个问题的，还在测试中。

**Comment by ho229v3666** [comment]
需要抓取的数据类型差不多是一样的吧
更新解析不同数据的正则表达式可不可以实现呢

**Comment by SkyD666** [comment]
> 需要抓取的数据类型差不多是一样的吧
> 更新解析不同数据的正则表达式可不可以实现呢

你可以看源代码里的Model那些类，还是比较复杂的，没找到一般的规律

**Comment by ho229v3666** [comment]
好的，辛苦了

**Comment by SkyD666** [comment]
[app_release_github_v1.1.3_beta3.zip](https://github.com/SkyD666/Imomoe/files/6932734/app_release_github_v1.1.3_beta3.zip)
如果愿意的话，你可以试试这个测试版本（使用之前备份好旧版本的重要数据，不保证不发生崩溃）。安装后将CustomDataSource.jar文件放在/storage/emulated/0/Android/data/com.skyd.imomoe/files/DataSourceJar/CustomDataSource.jar此处，然后在“设置”里面打开“自定义数据源”开关并重启APP，正常的话会看到https://www.yhdmp.net/ 的数据。
另外自定义数据源的观看历史和收藏与默认的 不 通 用 ！

**Comment by ho229v3666** [comment]
辛苦了辛苦了😂

**Comment by SkyD666** [comment]
v1.2.0版本已上线。如需使用此版本及更新的版本，请务必使用新版Jar包https://github.com/SkyD666/Imomoe/blob/master/doc/customdatasource/sample/custom/CustomDataSource.jar 替换上面回复的旧版Jar包，否则会APP崩溃
