### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by ZhuChengrui2004** [SkyD666/Imomoe#14]
建议加入自动播放上次集数，自动跳转到上次观看位置的功能
还有就是，我有个关于账号系统的设想，可以考虑下 账户是本地的，不需要中心服务器，账户文件是可以导入导出app的文件，这个文件里记录了头像昵称、追番、观看记录搜索记录、设置和主题等个人信息，更换设备或重新安装时把账户文件导入进去就行了

**Comment by SkyD666** [comment]
从观看历史或追番界面进入就是上次的集数

**Comment by SkyD666** [comment]
1.3.0_Akarin版本支持保存视频观看进度。可以尝试通过拷贝数据库来实现导入导出数据。
https://github.com/SkyD666/Imomoe/releases/tag/20
