### ISSUE TITLE
适配一下横屏（平板）吧

### ISSUE THREAD

**Issue by maplejaw** [SkyD666/Imomoe#15]
目前横屏布局封面裁切严重。播放界面更离谱，播放器太小了，只能全屏看。然后播放界面全屏旋转逻辑也有问题，横屏时点击全屏观看，然后再点回来，变成竖屏了。

**Comment by SkyD666** [comment]
[app_release_github_Panda(1.2.4).zip](https://github.com/SkyD666/Imomoe/files/7274161/app_release_github_Panda.1.2.4.zip)
试试这个

**Comment by maplejaw** [comment]
> [app_release_github_Panda(1.2.4).zip](https://github.com/SkyD666/Imomoe/files/7274161/app_release_github_Panda.1.2.4.zip) 试试这个

用的就是这个版本啊

**Comment by SkyD666** [comment]
https://github.com/SkyD666/Imomoe/releases/tag/1.2.5_Akarin
1.2.5_Akarin正式版进行了部分适配
