### ISSUE TITLE
Android11缓存视频视频失败

### ISSUE THREAD

**Issue by MisakaSakura** [SkyD666/Imomoe#2]
![Screenshot_20210411-211249_樱花动漫.png](https://user-images.githubusercontent.com/30547550/114305432-c579bc80-9b0a-11eb-9876-a023774085fe.png)![Screenshot_20210411-211438_权限控制器.png](https://user-images.githubusercontent.com/30547550/114305521-feb22c80-9b0a-11eb-92bd-eabe496a313b.png)

失败截图及提示信息，已授予存储权限

**Comment by SkyD666** [comment]
收到反馈

**Comment by SkyD666** [comment]
请问是什么型号的手机？

**Comment by MisakaSakura** [comment]
> 请问是什么型号的手机
红米K20Pro![Screenshot_20210413-113125_设置.png](https://user-images.githubusercontent.com/30547550/114492781-d4b45380-9c4b-11eb-9a93-dfe27caf2366.png)

**Comment by SkyD666** [comment]
由于没有安卓11系统的手机，因此我用安卓11模拟器（并不是Havoc-OS）测试缓存功能，然而并没有发现这个问题，不知道是不是Havoc-OS的问题
![QQ图片20210413163515](https://user-images.githubusercontent.com/32453770/114523076-8bc5c480-9c76-11eb-9c8a-987a81deaf05.png)
![QQ图片20210413163531](https://user-images.githubusercontent.com/32453770/114523102-93856900-9c76-11eb-92b8-ee80e7be08e3.png)
![QQ图片20210413163534](https://user-images.githubusercontent.com/32453770/114523105-941dff80-9c76-11eb-8b9d-daa04084ce60.png)
![QQ截图20210413163655](https://user-images.githubusercontent.com/32453770/114523108-954f2c80-9c76-11eb-9545-aa77cefc26fd.png)

**Comment by MisakaSakura** [comment]
我又试了还是不行，不知道有什么办法抓取日志吗？我可以提供一下日志。另外我手机上安装有存储重定向，但是并未将该软件重定向

**Comment by SkyD666** [comment]
> 我又试了还是不行，不知道有什么办法抓取日志吗？我可以提供一下日志。另外我手机上安装有存储重定向，但是并未将该软件重定向

是否介意通过qq或者其他更方便的方式来沟通这个问题？

**Comment by MisakaSakura** [comment]
应该没问题，这两天也放假

**Comment by SkyD666** [comment]
> 应该没问题，这两天也放假

QQ1161046314

**Comment by MisakaSakura** [comment]
作者已修复
