### ISSUE TITLE
下载了CustomDataSource1.ads但是软件里说“无效源文件后缀”

### ISSUE THREAD

**Issue by SCPf-166** [SkyD666/Imomoe#28]
如题
![IMG_20220112_194157](https://user-images.githubusercontent.com/97646865/149250632-71c78f44-66fd-4947-a98f-aaface72cf38.jpg)
![IMG_20220112_194130](https://user-images.githubusercontent.com/97646865/149250635-6367e60c-b7c5-4dbd-913b-e49cdad78920.jpg)

**Comment by SkyD666** [comment]
什么手机型号和安卓版本？

**Comment by SkyD666** [comment]
![Screenshot_20220113_142439_com.cxinventor.file.explorer.jpg](https://user-images.githubusercontent.com/32453770/149276887-25202f28-ca94-4d87-8f21-24f3956b9647.jpg)
![Screenshot_20220113_142447_com.cxinventor.file.explorer.jpg](https://user-images.githubusercontent.com/32453770/149276904-165ab539-bdac-4546-a127-0a835b087973.jpg)
你直接把ads放任这个文件夹也行

**Comment by SCPf-166** [comment]
> 什么手机型号和安卓版本？

![Screenshot_2022-01-13-01-21-24-33_fc704e6b13c4fb26bf5e411f75da84f2.jpg](https://user-images.githubusercontent.com/97646865/149283960-1a115f36-d946-4101-a64a-5bfc9068dc51.jpg)
我试一下你说的另一种方法

**Comment by SCPf-166** [comment]
使用了您刚才给的方法，可以导入了，但是导入之后ads就被变成0b大小并无法使用了

**Comment by SkyD666** [comment]
> 使用了您刚才给的方法，可以导入了，但是导入之后ads就被变成0b大小并无法使用了

你放到那个文件夹后不要再点击了，放入文件夹后直接重新切换到app界面，选择放入的那个ads文件就好了（也就是说导入功能相当于是把ads文件放到上述文件夹，我说的另一种方法就是相当于手动导入）

**Comment by SCPf-166** [comment]
按照您的方法操作之后现在可以用了，感谢大佬指导

**Comment by lidawei97688** [comment]
我是用re管理器时候提示无效，用es管理器成功的，具体原因我也不清楚

**Comment by SkyD666** [comment]
> 我是用re管理器时候提示无效，用es管理器成功的，具体原因我也不清楚

估计是re管理器提供的文件uri有点问题，还需研究一下

**Comment by zhaozongwen** [comment]
请问在哪里下载ads包，我在示例里不会下载

**Comment by SkyD666** [comment]
直接使用“数据源商店”功能下载和使用数据源
