### ISSUE TITLE
希望可以添加外置播放器播放器的功能

### ISSUE THREAD

**Issue by sanchendumeng** [SkyD666/Imomoe#3]
mxplayer解码性能更好一点

**Comment by hanxin1997** [comment]
希望作者添加添加外置播放器播放器，想配合弹弹play看弹幕

**Comment by SkyD666** [comment]
> 希望作者添加添加外置播放器播放器，想配合弹弹play看弹幕

下个版本就有外置播放器了

**Comment by hanxin1997** [comment]
> > 希望作者添加添加外置播放器播放器，想配合弹弹play看弹幕
> 
> 下个版本就有外置播放器了

感谢作者深夜回复消息，感谢作者开发这么棒的软件，早点休息，晚安。

**Comment by SkyD666** [comment]
v1.1.0实现此功能
