### ISSUE TITLE
大佬，导入显示这个，能指导下咋操作吗

### ISSUE THREAD

**Issue by Sakuraicy** [SkyD666/Imomoe#36]
大佬，导入显示这个，能指导下咋操作吗

> `
![WechatIMG32](https://user-images.githubusercontent.com/37129884/149689902-d81ba3e2-0cf9-441c-9d70-dcbd1e3ab0cb.jpeg)
`

**Comment by SkyD666** [comment]
https://github.com/SkyD666/Imomoe/issues/28
手动导入数据源

**Comment by SkyD666** [comment]
https://github.com/SkyD666/Imomoe/issues/38
