### ISSUE TITLE
无法导入ads文件

### ISSUE THREAD

**Issue by zhanggl666** [SkyD666/Imomoe#37]
![image](https://user-images.githubusercontent.com/12710539/149698275-7365f7e6-5930-4fc1-8cf1-b3880bffb7b2.png)

**Comment by SkyD666** [comment]
#28
手动导入数据源

**Comment by SkyD666** [comment]
https://github.com/SkyD666/Imomoe/issues/38

**Comment by zhanggl666** [comment]
好的， 我试试。。。
