### ISSUE TITLE
关于如何导入数据源的问题

### ISSUE THREAD

**Issue by SkyD666** [SkyD666/Imomoe#38]
两种方式：
1. 自动导入：用APP打开ads文件
2. 手动导入：手动拷贝文件

**Comment by SkyD666** [comment]
1. 自动导入
具体操作请见此处https://github.com/SkyD666/Imomoe/tree/master/doc/customdatasource#%E4%B8%80-%E4%BD%BF%E7%94%A8%E5%B7%B2%E6%9C%89%E7%9A%84%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E6%BA%90

**Comment by SkyD666** [comment]
2. 手动导入
手动将ads文件拷贝至此处：/storage/emulated/0/Android/data/com.skyd.imomoe/files/DataSourceJar
然后进入APP的更多-设置-自定义数据源页面，选择上述拷贝的ads文件即可。

**Comment by ailiheizi** [comment]
手动导入
版本：1.2.5_Akarin
![Screenshot_20220203-191624_MT管理器](https://user-images.githubusercontent.com/62006632/152333119-cfad8121-b006-4ac7-80fb-480dd2e5f289.png)
![Screenshot_20220203-191649_樱花动漫](https://user-images.githubusercontent.com/62006632/152333145-0402d441-bb7d-4f78-adad-0c1dfb9c6ad7.png)
重启软件后也是找不到数据源

**Comment by SkyD666** [comment]
> 手动导入 版本：1.2.5_Akarin ![Screenshot_20220203-191624_MT管理器](https://user-images.githubusercontent.com/62006632/152333119-cfad8121-b006-4ac7-80fb-480dd2e5f289.png) ![Screenshot_20220203-191649_樱花动漫](https://user-images.githubusercontent.com/62006632/152333145-0402d441-bb7d-4f78-adad-0c1dfb9c6ad7.png) 重启软件后也是找不到数据源

发个文件夹的完整路径看看

**Comment by SkyD666** [comment]
> 手动导入 版本：1.2.5_Akarin ![Screenshot_20220203-191624_MT管理器](https://user-images.githubusercontent.com/62006632/152333119-cfad8121-b006-4ac7-80fb-480dd2e5f289.png) ![Screenshot_20220203-191649_樱花动漫](https://user-images.githubusercontent.com/62006632/152333145-0402d441-bb7d-4f78-adad-0c1dfb9c6ad7.png) 重启软件后也是找不到数据源

是不是没建立DataSourceJar文件夹？
