### ISSUE TITLE
那么问题来了，数据源哪里下载

### ISSUE THREAD

**Issue by KoedaNagi** [SkyD666/Imomoe#40]
……

**Comment by SkyD666** [comment]
使用方法请阅读此文档①-④：https://github.com/SkyD666/Imomoe/blob/master/doc/customdatasource/README.md

**Comment by SkyD666** [comment]
https://github.com/SkyD666/Imomoe/tree/master/doc/customdatasource/sample1
https://github.com/SkyD666/Imomoe/tree/master/doc/customdatasource/sample2
