### ISSUE TITLE
关于ads

### ISSUE THREAD

**Issue by KDXYuuHi** [SkyD666/Imomoe#48]
老哥
ads这玩意我实在搞不定 
app装上重置也没有你说的默认源
只有一个自定义源引导
属实是把我整蒙了!
所以我想能否给的ads数据源（b站 樱花都行）
![Screenshot_20220128-192115.png](https://user-images.githubusercontent.com/95617454/151538574-e34e02c3-8942-4f67-b263-705e58824cfd.png)

**Comment by SkyD666** [comment]
https://github.com/SkyD666/Imomoe/blob/master/doc/customdatasource/README.md
看这个①-④

**Comment by SkyD666** [comment]
以下两个链接有ads
https://github.com/SkyD666/Imomoe/tree/master/doc/customdatasource/sample1
https://github.com/SkyD666/Imomoe/tree/master/doc/customdatasource/sample2

**Comment by KDXYuuHi** [comment]
> 以下两个链接有ads
> https://github.com/SkyD666/Imomoe/tree/master/doc/customdatasource/sample1
> https://github.com/SkyD666/Imomoe/tree/master/doc/customdatasource/sample2

又出现新情况了
播放有视频 下载就成了几k的音频了![Screenshot_20220128-212830.png](https://user-images.githubusercontent.com/95617454/151555144-bef1db76-86a5-4c90-a980-6e8b978bf51c.png)![Screenshot_20220128-212753.png](https://user-images.githubusercontent.com/95617454/151555151-f0d9bc6f-bfab-484e-bebb-da7be99679f3.png)![Screenshot_20220128-212753.png](https://user-images.githubusercontent.com/95617454/151555252-df805441-eb2b-4e0c-b1f2-d1e2a41aabb4.png)

**Comment by SkyD666** [comment]
> > 以下两个链接有ads
> > https://github.com/SkyD666/Imomoe/tree/master/doc/customdatasource/sample1
> > https://github.com/SkyD666/Imomoe/tree/master/doc/customdatasource/sample2
> 
> 又出现新情况了 播放有视频 下载就成了几k的音频了![Screenshot_20220128-212830.png](https://user-images.githubusercontent.com/95617454/151555144-bef1db76-86a5-4c90-a980-6e8b978bf51c.png)![Screenshot_20220128-212753.png](https://user-images.githubusercontent.com/95617454/151555151-f0d9bc6f-bfab-484e-bebb-da7be99679f3.png)![Screenshot_20220128-212809.png](https://user-images.githubusercontent.com/95617454/151555350-23971277-884e-48ec-8abc-752ad8a5cd1c.png)

m3u8是一系列视频的目录，目前暂不支持m3u8格式下载。
可以尝试使用其他工具解析m3u8文件来下载

**Comment by KDXYuuHi** [comment]
> > > 以下两个链接有ads
> > > https://github.com/SkyD666/Imomoe/tree/master/doc/customdatasource/sample1
> > > https://github.com/SkyD666/Imomoe/tree/master/doc/customdatasource/sample2
> > 
> > 又出现新情况了 播放有视频 下载就成了几k的音频了![Screenshot_20220128-212830.png](https://user-images.githubusercontent.com/95617454/151555144-bef1db76-86a5-4c90-a980-6e8b978bf51c.png)![Screenshot_20220128-212753.png](https://user-images.githubusercontent.com/95617454/151555151-f0d9bc6f-bfab-484e-bebb-da7be99679f3.png)![Screenshot_20220128-212809.png](https://user-images.githubusercontent.com/95617454/151555350-23971277-884e-48ec-8abc-752ad8a5cd1c.png)
> 
> m3u8是一系列视频的目录，目前暂不支持m3u8格式下载。
> 可以尝试使用其他工具解析m3u8文件来下载

就是我得用其他下载器去下载了是吧

**Comment by SkyD666** [comment]
用专门下载m3u8的下载器就行

**Comment by KDXYuuHi** [comment]
> 用专门下载m3u8的下载器就行

ojbk 感谢老哥
