### ISSUE TITLE
安装的是最新版，手机资源管理器找不到com.skyd.imomoe这个文件夹😭

### ISSUE THREAD

**Issue by Rimesal** [SkyD666/Imomoe#49]
自动整理数据源不成功，所以想用您写的手动方法，但是找不到文件夹位置

**Comment by Rimesal** [comment]
用es文件管理器找到了Android/data/com.sky.imomoe/files这个路径，但是files这个文件夹里面没有您在其他回答里贴图显示的oat文件夹（不知道这个问题是否重要）。而且我把两个.ads文件移动到这里，再打开樱花app-设置-自定义数据源，页面是空哒😅

**Comment by SkyD666** [comment]
需要手动创建文件夹。

另外注意是这个目录下的![Screenshot_20220129_101839.jpg](https://user-images.githubusercontent.com/32453770/151643514-8e113557-0862-4ec6-9422-99793a58112c.jpg)

**Comment by Rimesal** [comment]
> 

嗯，成功了。谢谢回复🙏
