### ISSUE TITLE
使用后反馈

### ISSUE THREAD

**Issue by mofomake** [SkyD666/Imomoe#5]
一：缓存列表排序有瑕疵，应该是只对比了前两位数，如：100会排在99前面
二：发现集数太多时，前面集数无法缓存，提示没有相关地址和主机名，不知道是不是因为樱花获取视频链接的问题，如名侦探柯南1000集前基本下载不了
三：我不知道算不算问题，因为我多次尝试无法复现，有一次缓存后播放出现音视频不同步，换成浏览器播放就没问题，后续没有发现此问题
小建议：
1.建议对播放器增加一个功能：按住就能倍速播放，因为有时候想跳着看却只能托进度条，倍速播放只能去点击
2.下载功能可以改进，因为有时来消息清除时会同时清除掉下载列表导致中止下载

最后还是挺感谢作者提供的这个软件， Android端这种软件挺不好找的

**Comment by SkyD666** [comment]
一和三是bug。二的话，你可以试试浏览器能不能播放，如果能的话就是bug（一般来说能播就能下）
1没看懂什么意思
2可以改进

（用心提这么多问题还是很感动）

**Comment by SkyD666** [comment]
一和三可以给出网址链接我试试（通过分析-复制链接）

**Comment by mofomake** [comment]
刚看了下，确实时樱花的问题播放不了
建议1的话就是类似夸克的播放器按住屏幕会进行倍速播放，松开就会正常播放，因为有时候想快一点只有两种办法，1.拖动进度条 2.先点击倍速然后选择多少倍速播放。

**Comment by mofomake** [comment]
一的话是http://www.yhdm.io/show/1654.html，下载到100后会出现排序
三的话http://www.yhdm.io/show/5219.html，这一现象只在我第一天时候出现，后面想复现也复现不来

**Comment by SkyD666** [comment]
v1.1.0修复了问题一和1

**Comment by SkyD666** [comment]
可使用v1.1.1看是否修复了问题三
