### ISSUE TITLE
建议以及问题

### ISSUE THREAD

**Issue by yimiyg** [SkyD666/Imomoe#53]
建议：1. 推荐动漫部分比较单一，和动画本身缺少联系

问题：1. 动漫名部分相比之前出现了很多乱码

**Comment by SkyD666** [comment]
推荐动漫是网站的推荐，软件无法控制。

**Comment by SkyD666** [comment]
乱码问题1.3.0_Akarin版本解决
https://github.com/SkyD666/Imomoe/releases/tag/20
