### ISSUE TITLE
视频播放中出现报错提示

### ISSUE THREAD

**Issue by ysy5779** [SkyD666/Imomoe#55]
![Screenshot_2022-02-09-08-26-21-600_com skyd imomoe](https://user-images.githubusercontent.com/40509650/153098724-3d17ec89-13d9-4780-a858-b11f4e0ea748.jpg)
数据源播放经常出现图中的提示。请大佬帮忙看看

**Comment by SkyD666** [comment]
这种情况一般是网络不佳问题或者视频资源本身的问题，不影响观看不必关注，若影响，可以尝试退出后再次进入。
