### ISSUE TITLE
当动漫更新最新一集的时候,这个App会自动更新吗?

### ISSUE THREAD

**Issue by feng99** [SkyD666/Imomoe#62]
当动漫更新最新一集的时候,这个App会自动更新吗?

**Comment by SkyD666** [comment]
这个App本质就是显示樱花动漫网页的数据，所以网页更新后App显示的内容也会更新

**Comment by feng99** [comment]
> 

您好,这个樱花动漫,我百度一下,发现有很多同名网站,  这个app对于的是哪一个网站呀?  域名是什么呢?  谢谢

**Comment by SkyD666** [comment]
网站页面一样的话，编写数据源，就都能用

**Comment by SkyD666** [comment]
没有固定的网站，可以更换
