### ISSUE TITLE
m3u8格式的视频url无法播放，提示获取数据失败

### ISSUE THREAD

**Issue by geneliunx** [SkyD666/Imomoe#63]
m3u8格式的视频url无法播放，提示获取数据失败
mp4格式的就可以正常播放
网页版yinghuacd.com是正常播放的
http://www.yinghuacd.com/v/5507-6.html
![image](https://user-images.githubusercontent.com/29857428/154037165-254cf07f-8e08-4228-a90c-387bf1f93a90.png)

**Comment by SkyD666** [comment]
https://github.com/SkyD666/Imomoe/releases/download/19/CustomDataSource1.ads
下载这个，更新一下数据源试试

**Comment by geneliunx** [comment]
也不行，prerelease版本也不行，用对应的数据源，都会出现这个

**Comment by SkyD666** [comment]
我试了一下我打开这个页面能播放
![Screenshot_20220215_214013_com skyd imomoe](https://user-images.githubusercontent.com/32453770/154073481-229ed98a-bdca-4ff5-9601-15dbe0ab95d8.jpg)

**Comment by SkyD666** [comment]
原因未知，要不换一台手机试试？

**Comment by geneliunx** [comment]
小米10pro MIUI13 Android12
只有自带的浏览器能播放，第三方浏览器也不行
mumu模拟器也不行
雷电模拟器可以，chrome直接访问url不行
所以这是啥原因，是手机缺少啥依赖吗

**Comment by SkyD666** [comment]
我在电脑上试了，edge可以，chrome播不了，IE也播不了
不知道什么原因，但是感觉跟网站有关系

**Comment by geneliunx** [comment]
更新了最新的1.3.0release他又可以了，也不知道是不是跟我系统更新有关
