### ISSUE TITLE
两个小问题

### ISSUE THREAD

**Issue by zhangjk01** [SkyD666/Imomoe#70]
1.收藏夹是否能导入导出
2.未来是否考虑加入WebDAV服务来进行不同设备间的收藏夹和观看记录同步

**Comment by SkyD666** [comment]
这两项，后续会考虑

**Comment by CharlesIX2022** [comment]
歪比歪比？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月27日(周日) 晚上6:42
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [SkyD666/Imomoe] 两个小问题 (Issue #70)




 
这两项，后续会考虑
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kong279** [comment]
导入不进去怎么办啊

**Comment by kong279** [comment]
作者导入的时候一直显示导入失败

**Comment by SkyD666** [comment]
> 作者导入的时候一直显示导入失败

有截图吗

**Comment by kong279** [comment]
有截屏但是发不出去

**Comment by kong279** [comment]
我导入了三四次

**Comment by kong279** [comment]
我把1.25版本也下载了，也是导入数据失败

**Comment by SkyD666** [comment]
> 我把1.25版本也下载了，也是导入数据失败

用releas里面的1.3.1

**Comment by SkyD666** [comment]
> 我把1.25版本也下载了，也是导入数据失败

https://github.com/SkyD666/Imomoe/releases/tag/21

**Comment by kong279** [comment]
导入进去了，谢谢作者，作者您辛苦了

**Comment by mr-mihu** [comment]
> > 我把1.25版本也下载了，也是导入数据失败
> 
> https://github.com/SkyD666/Imomoe/releases/tag/21

1. 最新版1.3.1导入数据源失败，跳转界面后没反应，需要手动移动文件到DataSourceJar目录。测试问题机型小米5魔趣系统和红米k30
2. DataSourceJar目录不会自动创建吗

**Comment by SkyD666** [comment]
> 

确实有1这个问题，原因未知。但是多试几次可以显示导入对话框，比较奇怪

**Comment by SkyD666** [comment]
> > > 我把1.25版本也下载了，也是导入数据失败
> > 
> > 
> > https://github.com/SkyD666/Imomoe/releases/tag/21
> 
> 1. 最新版1.3.1导入数据源失败，跳转界面后没反应，需要手动移动文件到DataSourceJar目录。测试问题机型小米5魔趣系统和红米k30
> 2. DataSourceJar目录不会自动创建吗

确实有1这个问题，但是多次尝试有几率显示导入对话框，原因未知

**Comment by SkyD666** [comment]
> > > 我把1.25版本也下载了，也是导入数据失败
> > 
> > 
> > https://github.com/SkyD666/Imomoe/releases/tag/21
> 
> 1. 最新版1.3.1导入数据源失败，跳转界面后没反应，需要手动移动文件到DataSourceJar目录。测试问题机型小米5魔趣系统和红米k30
> 2. DataSourceJar目录不会自动创建吗

打了个新版apk（版本没变），试试这个
[app_release_github_1.3.1_Akarin.zip](https://github.com/SkyD666/Imomoe/files/8237277/app_release_github_1.3.1_Akarin.zip)

**Comment by mr-mihu** [comment]
> 
可以，测试没问题

**Comment by SkyD666** [comment]
WebDAV请尝试此版本：
https://github.com/SkyD666/Imomoe/releases/tag/22

**Comment by mr-mihu** [comment]
> WebDAV： https://github.com/SkyD666/Imomoe/releases/tag/22

切换数据源后历史记录无法播放，
建议隐藏，或者保留历史记录所在源的域名

**Comment by SkyD666** [comment]
> > WebDAV： https://github.com/SkyD666/Imomoe/releases/tag/22
> 
> 切换数据源后历史记录无法播放，
> 建议隐藏，或者保留历史记录所在源的域名

有几个问题，一是目前历史记录没有保存域名；二是如果保存了域名，万一数据源更新后域名换了但是网站没换就检测不到之前的记录了
