### ISSUE TITLE
[BUG] 最新 1.4.0_Akarin测试版 启动时无限循环

### ISSUE THREAD

**Issue by EvatsugDnalloR** [SkyD666/Imomoe#76]
描述：最新 1.4.0_Akarin测试版 启动时无法启动，无限循环启动画面

安卓版本：安卓11，OneUI 3.1

[log.txt](https://github.com/SkyD666/Imomoe/files/8458713/log.txt)
（截取了一小段的崩溃日志... 希望有帮助。如果需要完整崩溃日志也可以之后发出来）

**Comment by SkyD666** [comment]
[app_release_github_1.4.0_Akarin.zip](https://github.com/SkyD666/Imomoe/files/8458925/app_release_github_1.4.0_Akarin.zip)
你试试这个没混淆版本的

**Comment by EvatsugDnalloR** [comment]
> [app_release_github_1.4.0_Akarin.zip](https://github.com/SkyD666/Imomoe/files/8458925/app_release_github_1.4.0_Akarin.zip) 你试试这个没混淆版本的

还是一样无限循环...
[log.txt](https://github.com/SkyD666/Imomoe/files/8458953/log.txt)

**Comment by EvatsugDnalloR** [comment]
顺便说一句退回1.3.1一切正常

**Comment by SkyD666** [comment]
> 顺便说一句退回1.3.1一切正常

这个肯定，因为我看到是某个新功能涉及到这个bug

**Comment by SkyD666** [comment]
[app_release_github_1.4.0_Akarin.zip](https://github.com/SkyD666/Imomoe/files/8459103/app_release_github_1.4.0_Akarin.zip)
再试试这个，按理来说应该可以了

**Comment by EvatsugDnalloR** [comment]
> [app_release_github_1.4.0_Akarin.zip](https://github.com/SkyD666/Imomoe/files/8459103/app_release_github_1.4.0_Akarin.zip)
> 再试试这个，按理来说应该可以了

成功了，感谢
![Screenshot_20220410-155022.jpg](https://user-images.githubusercontent.com/86464406/162621404-2df1813f-8950-45ab-8e3a-ac645f800c9e.jpg)

**Comment by SkyD666** [comment]
你最好试试“设置”界面切换播放器内核功能正不正常，当然，如果你用不到这个功能的话也可以不用管

**Comment by EvatsugDnalloR** [comment]
> 你最好试试“设置”界面切换播放器内核功能正不正常，当然，如果你用不到这个功能的话也可以不用管

测试了一下确实有问题，在数据源1的情况下使用ijk内核播放会黑屏，但声音正常；用系统内核会直接获取数据失效。但exoplayer内核播放正常

**Comment by SkyD666** [comment]
> > 你最好试试“设置”界面切换播放器内核功能正不正常，当然，如果你用不到这个功能的话也可以不用管
> 
> 测试了一下确实有问题，在数据源1的情况下使用ijk内核播放会黑屏，但声音正常；用系统内核会直接获取数据失效。但exoplayer内核播放正常

这个问题超出我的知识领域了，属于音视频开发的东西了，可能是视频的问题，也可能是内核的问题（刚才我的意思是看看切换内核会不会成功）

**Comment by EvatsugDnalloR** [comment]
> > > 你最好试试“设置”界面切换播放器内核功能正不正常，当然，如果你用不到这个功能的话也可以不用管
> > 
> > 测试了一下确实有问题，在数据源1的情况下使用ijk内核播放会黑屏，但声音正常；用系统内核会直接获取数据失效。但exoplayer内核播放正常
> 
> 这个问题超出我的知识领域了，属于音视频开发的东西了，可能是视频的问题，也可能是内核的问题（刚才我的意思是看看切换内核会不会成功）

是切换播放器内核会不会成功吗？那应该是成功的...

**Comment by SkyD666** [comment]
那应该没事，至于不同内核有不同的问题，这个确实解决不了
