### ISSUE TITLE
作者大大，无法下载动漫

### ISSUE THREAD

**Issue by 1536743595** [SkyD666/Imomoe#77]
![IMG_20220410_183212](https://user-images.githubusercontent.com/103361825/162614030-c6f15608-f2be-4a05-b6dc-867ed0629439.jpg)
![Screenshot_2022-04-10-18-31-39-68_bb02debb102c541e887ce32968b170eb](https://user-images.githubusercontent.com/103361825/162614042-fe8c17b4-f4cd-4e38-bcd5-814b1c1e53b0.jpg)
![Screenshot_2022-04-10-18-31-35-53_bb02debb102c541e887ce32968b170eb](https://user-images.githubusercontent.com/103361825/162614044-449210ef-8369-4fd1-b4c3-97db07dc3fe5.jpg)

**Comment by 1536743595** [comment]
点击下载，显示第一张图片

**Comment by 1536743595** [comment]
@天际D666

**Comment by SkyD666** [comment]
等提示开始下载再关闭页面试试

**Comment by 1536743595** [comment]
还是不行，😂，回复好快@skyD666

**Comment by 1536743595** [comment]
还是不行，😂，回复好快@skyD666

**Comment by SkyD666** [comment]
这个视频能播放吗

**Comment by 1536743595** [comment]
视频可以播放

**Comment by SkyD666** [comment]
你看看系统设置里允许显示APP通知吗？

**Comment by 1536743595** [comment]
> 你看看系统设置里允许显示APP通知吗？

看了一下，是不允许状态，这个有影响吗

**Comment by SkyD666** [comment]
你打开试试

**Comment by 1536743595** [comment]
> 你打开试试

好的，我再试试

**Comment by 1536743595** [comment]
> 你打开试试

可以下载了，非常神奇，多谢😘

**Comment by mr-mihu** [comment]
> 你看看系统设置里允许显示APP通知吗？

能加一下功能吗，第一次安装app弹窗让用户点击授权，还得手动打开

**Comment by SkyD666** [comment]
> > 你看看系统设置里允许显示APP通知吗？
> 
> 能加一下功能吗，第一次安装app弹窗让用户点击授权，还得手动打开

行

**Comment by mr-mihu** [comment]
1.4.0版无法导入数据源；
点击数据源文件，打开列表里没有app

**Comment by 1536743595** [comment]
> 1.4.0版无法导入数据源； 点击数据源文件，打开列表里没有app

兄弟问下，1.40版本哪里下载

**Comment by mr-mihu** [comment]
> > 1.4.0版无法导入数据源； 点击数据源文件，打开列表里没有app
> 
> 兄弟问下，1.40版本哪里下载

https://github.com/SkyD666/Imomoe/releases

**Comment by 1536743595** [comment]
> 



> 
好的

**Comment by SkyD666** [comment]
> 1.4.0版无法导入数据源； 点击数据源文件，打开列表里没有app

这个版本app识别的是二进制文件（例如APP不会显示在文本的打开方式中），你看看是不是选择的类型不对

**Comment by mr-mihu** [comment]
> > 1.4.0版无法导入数据源； 点击数据源文件，打开列表里没有app
> 
> 这个版本app识别的是二进制文件（例如APP不会显示在文本的打开方式中），你看看是不是选择的类型不对

文本、音频、视频、图像，都试过了，都不显示

**Comment by SkyD666** [comment]
那等等还是改回来吧（本来想着不在多余的类型里面显示）
你看看有没有“全部”类型
![](https://user-images.githubusercontent.com/32453770/162616032-b9d9c95f-5a1c-43ae-92b1-2b98b0e13f29.jpg)

**Comment by mr-mihu** [comment]
> 那等等还是改回来吧（本来想着不在多余的类型里面显示） 你看看有没有“全部”类型 ![](https://user-images.githubusercontent.com/32453770/162616032-b9d9c95f-5a1c-43ae-92b1-2b98b0e13f29.jpg)

没有，至少我这个红米K30Pro没有

**Comment by SkyD666** [comment]
> > 那等等还是改回来吧（本来想着不在多余的类型里面显示） 你看看有没有“全部”类型 ![](https://user-images.githubusercontent.com/32453770/162616032-b9d9c95f-5a1c-43ae-92b1-2b98b0e13f29.jpg)
> 
> 没有，至少我这个红米K30Pro没有

你试试新版预发行apk
