### ISSUE TITLE
1.4.0怎么用新数据源呀？

### ISSUE THREAD

**Issue by roulen100** [SkyD666/Imomoe#83]
大佬好呀，感谢提供的APP！

请咨询一下，我的APP版本：1.4.0_Akarin，数据源接口版本：202202121320

当下载了数据源仓库中202202121320里面的“CustomDataSource1.ads”和henniu-sese.ads提示不匹配，并且删除后再恢复后也没有数据。

只能重新下载Assets里面的CustomDataSource1.ads  是我姿势不对吗？

**Comment by roulen100** [comment]
> 目前使用版本：1.4.0_Akarin，数据源接口版本：202202121320 怎么使用202204191624的数据源呀？

是不是要等你发新版能可以用呢？（外行）

**Comment by SkyD666** [comment]
数据源仓库有新版本的ads

**Comment by SkyD666** [comment]
把之前的数据源先删除再倒入新的试试
