### ISSUE TITLE
快进很卡顿

### ISSUE THREAD

**Issue by roulen100** [SkyD666/Imomoe#84]
1.4.0版本，使用默认的设置。
在播放影片时，下载进度条已经缓存很长一段，但是向右滑动快进几秒时，大概很卡顿2到3秒，所有影片都是这样，之前版本没有这个情况。

感谢大佬的付出！

**Comment by SkyD666** [comment]
在设置界面把播放器内核换成exoplayer试试

**Comment by SkyD666** [comment]
使用1.7.0版本并在设置页面使用ExoPlayer内核即可解决
