### ISSUE TITLE
播放器页面屏幕锁定后仍然可以操作

### ISSUE THREAD

**Issue by tapttr** [SkyD666/Imomoe#87]
![IMG20220514121001.jpg](https://user-images.githubusercontent.com/49118409/168410298-5135cf68-7e15-4f82-9c9d-544b653edf30.jpg)![Screenshot_2022-05-14-12-15-09-695_com.skyd.imomoe.jpg](https://user-images.githubusercontent.com/49118409/168410350-4d8e6922-cad4-4721-a26a-056bdba30976.jpg)
红米k40 miui13.0.5 软件1.5.0（1.4.0)

**Comment by SkyD666** [comment]
https://github.com/SkyD666/Imomoe/releases/download/23/app_release_github_1.5.0_Akarin.apk
这个应该修复了

**Comment by tapttr** [comment]
这个版本正常了
