### ISSUE TITLE
播放中断网会出现离奇的bug，具体看视频吧

### ISSUE THREAD

**Issue by tapttr** [SkyD666/Imomoe#89]
https://user-images.githubusercontent.com/49118409/169632988-351de068-42d4-48dc-a840-92963bb83cb4.mp4

**Comment by tapttr** [comment]
然后过一段时间应用会崩溃闪退

**Comment by SkyD666** [comment]
你是指那块闪动的白块吗

**Comment by SkyD666** [comment]
https://user-images.githubusercontent.com/32453770/169633962-707ee481-1519-42c0-8191-dc23850cf7f3.mp4

**Comment by SkyD666** [comment]
印象中我没有设置这个白块

**Comment by tapttr** [comment]
应该是等自己播放到缓冲的地方，这个白块![IMG20220521114616.jpg](https://user-images.githubusercontent.com/49118409/169634213-0a956aa5-5871-4e4e-b0b6-e7166e74efc5.jpg)看图形应该是樱花的应用程序吧![IMG20220521114738.jpg](https://user-images.githubusercontent.com/49118409/169634251-d93f33c0-1928-4444-927b-9aeec7f4cbd8.jpg)，另外需要发log吗

**Comment by SkyD666** [comment]
发一下log吧

**Comment by tapttr** [comment]
有讨论群或者频道吗，议题里不能上传log文件，感觉这样交流很麻烦🧐

**Comment by SkyD666** [comment]
暂时没有，你可以把文件打包成zip

**Comment by SkyD666** [comment]
我试了，是等自动播放完缓冲的部分，也没复现问题，你可以换台设备试试

**Comment by tapttr** [comment]
换了1.4.0和预发行的1.5.0都正常，只有上个议题你发的版本有问题，并且预发行的1.5.0播放器页面锁又正常了，似乎不用修了![Screenshot_2022-05-21-16-23-51-298_com.github.android.jpg](https://user-images.githubusercontent.com/49118409/169643072-6907d2f2-e05a-4e83-8d89-5f246bd90c2b.jpg)

**Comment by tapttr** [comment]
抱歉浪费了这么多时间

**Comment by SkyD666** [comment]
后面有问题再提issue吧

**Comment by SkyD666** [comment]
> 有讨论群或者频道吗，议题里不能上传log文件，感觉这样交流很麻烦🧐

Discard频道：https://discord.gg/MyaRtRGEzr
